export interface Ingredient {
  name: string;
  quantity: string;
  category: string;
}

export interface Recipe {
  id: string;
  name: string;
  description: string;
  servings: number;
  prepTime: number;
  cookTime: number;
  tags: string[];
  ingredients: Ingredient[];
  steps: string[];
  source: string;
}

export const RECIPES: Recipe[] = [
  {
    id: 'r1',
    name: 'Spaghetti Bolognese',
    description: 'Klassieke Italiaanse pasta met rijke vleessaus.',
    servings: 4,
    prepTime: 15,
    cookTime: 45,
    tags: ['pasta', 'italiaans', 'klassiek'],
    ingredients: [
      { name: 'Spaghetti', quantity: '400 g', category: 'conserven-pasta' },
      { name: 'Rundergehakt', quantity: '500 g', category: 'vlees-vis' },
      { name: 'Uien', quantity: '2', category: 'groente-fruit' },
      { name: 'Knoflook', quantity: '3 tenen', category: 'groente-fruit' },
      { name: 'Wortels', quantity: '2', category: 'groente-fruit' },
      { name: 'Selderij', quantity: '2 stengels', category: 'groente-fruit' },
      { name: 'Gepelde tomaten', quantity: '400 g', category: 'conserven-pasta' },
      { name: 'Tomatenpuree', quantity: '2 el', category: 'conserven-pasta' },
      { name: 'Olijfolie', quantity: '2 el', category: 'conserven-pasta' },
      { name: 'Parmezaan', quantity: '50 g', category: 'zuivel' },
    ],
    steps: [
      'Snipper de ui, wortel en selderij fijn.',
      'Fruit de groenten in olijfolie.',
      'Voeg het gehakt toe en bak bruin.',
      'Voeg tomatenpuree en gepelde tomaten toe.',
      'Laat 30 minuten sudderen op laag vuur.',
      'Kook de spaghetti volgens de verpakking.',
      'Serveer met geraspte Parmezaan.',
    ],
    source: 'Klassiek recept',
  },
  {
    id: 'r2',
    name: 'Pannenkoeken',
    description: 'Hollandse pannenkoeken, luchtig en goudbruin.',
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    tags: ['hollands', 'snel', 'kindvriendelijk'],
    ingredients: [
      { name: 'Bloem', quantity: '250 g', category: 'brood-bakkerij' },
      { name: 'Eieren', quantity: '3', category: 'zuivel' },
      { name: 'Melk', quantity: '500 ml', category: 'zuivel' },
      { name: 'Zout', quantity: '1 snufje', category: 'overig' },
      { name: 'Boter', quantity: '30 g', category: 'zuivel' },
    ],
    steps: [
      'Meng bloem, eieren, melk en zout tot een glad beslag.',
      'Laat 10 minuten rusten.',
      'Verhit boter in een koekenpan.',
      'Schep een lepel beslag in de pan en bak goudbruin.',
      'Draai om en bak de andere kant.',
    ],
    source: 'Hollands recept',
  },
  {
    id: 'r3',
    name: 'Caesar Salade',
    description: 'Frisse salade met knapperige croutons en romige dressing.',
    servings: 2,
    prepTime: 15,
    cookTime: 10,
    tags: ['salade', 'snel', 'licht'],
    ingredients: [
      { name: 'Sla', quantity: '1 krop', category: 'groente-fruit' },
      { name: 'Kipfilet', quantity: '200 g', category: 'vlees-vis' },
      { name: 'Parmezaan', quantity: '40 g', category: 'zuivel' },
      { name: 'Wit brood', quantity: '2 sneetjes', category: 'brood-bakkerij' },
      { name: 'Knoflook', quantity: '1 teen', category: 'groente-fruit' },
      { name: 'Olijfolie', quantity: '3 el', category: 'conserven-pasta' },
      { name: 'Citroenen', quantity: '1', category: 'groente-fruit' },
      { name: 'Mayonaise', quantity: '2 el', category: 'conserven-pasta' },
    ],
    steps: [
      'Snijd brood in blokjes, bak knapperig in olie met knoflook.',
      'Gril de kipfilet en snijd in reepjes.',
      'Meng mayo, citroensap, knoflook en Parmezaan voor de dressing.',
      'Scheur de sla en meng met dressing.',
      'Top met kip, croutons en extra Parmezaan.',
    ],
    source: 'Klassiek recept',
  },
  {
    id: 'r4',
    name: 'Tomatensoep',
    description: 'Romige tomatensoep met basilicum. Comfortfood op z\'n best.',
    servings: 4,
    prepTime: 10,
    cookTime: 30,
    tags: ['soep', 'vegetarisch', 'comfortfood'],
    ingredients: [
      { name: 'Tomaten', quantity: '800 g', category: 'groente-fruit' },
      { name: 'Uien', quantity: '1', category: 'groente-fruit' },
      { name: 'Knoflook', quantity: '2 tenen', category: 'groente-fruit' },
      { name: 'Groentebouillon', quantity: '500 ml', category: 'overig' },
      { name: 'Basilicum', quantity: '1 bosje', category: 'groente-fruit' },
      { name: 'Kookroom', quantity: '100 ml', category: 'zuivel' },
      { name: 'Olijfolie', quantity: '2 el', category: 'conserven-pasta' },
      { name: 'Suiker', quantity: '1 tl', category: 'overig' },
    ],
    steps: [
      'Fruit ui en knoflook in olijfolie.',
      'Voeg tomaten en bouillon toe.',
      'Kook 20 minuten en pureer glad.',
      'Roer de room erdoor.',
      'Garneer met verse basilicum.',
    ],
    source: 'Huisgemaakt',
  },
  {
    id: 'r5',
    name: 'Pad Thai',
    description: 'Thaise woknoedels met garnalen, pinda\'s en limoen.',
    servings: 2,
    prepTime: 15,
    cookTime: 10,
    tags: ['aziatisch', 'snel', 'wok'],
    ingredients: [
      { name: 'Noodles', quantity: '200 g', category: 'conserven-pasta' },
      { name: 'Garnalen', quantity: '200 g', category: 'vlees-vis' },
      { name: 'Eieren', quantity: '2', category: 'zuivel' },
      { name: 'Bosui', quantity: '3', category: 'groente-fruit' },
      { name: 'Pinda\'s', quantity: '50 g', category: 'snacks' },
      { name: 'Limoenen', quantity: '1', category: 'groente-fruit' },
      { name: 'Sojasaus', quantity: '2 el', category: 'conserven-pasta' },
      { name: 'Sriracha', quantity: '1 el', category: 'conserven-pasta' },
      { name: 'Zonnebloemolie', quantity: '2 el', category: 'conserven-pasta' },
    ],
    steps: [
      'Week de noodles in heet water.',
      'Bak garnalen in olie.',
      'Voeg ei toe en roerbak.',
      'Voeg noodles, sojasaus en sriracha toe.',
      'Serveer met pinda\'s, bosui en limoen.',
    ],
    source: 'Aziatisch recept',
  },
  {
    id: 'r6',
    name: 'Risotto met Champignons',
    description: 'Romige risotto met gebakken paddenstoelen.',
    servings: 4,
    prepTime: 10,
    cookTime: 35,
    tags: ['italiaans', 'vegetarisch', 'comfortfood'],
    ingredients: [
      { name: 'Risotto rijst', quantity: '300 g', category: 'conserven-pasta' },
      { name: 'Champignons', quantity: '300 g', category: 'groente-fruit' },
      { name: 'Uien', quantity: '1', category: 'groente-fruit' },
      { name: 'Knoflook', quantity: '2 tenen', category: 'groente-fruit' },
      { name: 'Groentebouillon', quantity: '1 liter', category: 'overig' },
      { name: 'Parmezaan', quantity: '60 g', category: 'zuivel' },
      { name: 'Boter', quantity: '30 g', category: 'zuivel' },
      { name: 'Witte wijn', quantity: '100 ml', category: 'dranken' },
      { name: 'Peterselie', quantity: '1 bosje', category: 'groente-fruit' },
    ],
    steps: [
      'Fruit ui en knoflook in boter.',
      'Bak champignons apart goudbruin.',
      'Voeg rijst toe en roer 1 minuut.',
      'Blus af met wijn.',
      'Voeg scheppen bouillon toe tot de rijst gaar is.',
      'Roer Parmezaan en champignons erdoor.',
    ],
    source: 'Italiaans recept',
  },
  {
    id: 'r7',
    name: 'Griekse Salade',
    description: 'Frisse salade met feta, olijven en tomaat.',
    servings: 2,
    prepTime: 10,
    cookTime: 0,
    tags: ['salade', 'vegetarisch', 'snel', 'grieks'],
    ingredients: [
      { name: 'Tomaten', quantity: '4', category: 'groente-fruit' },
      { name: 'Komkommer', quantity: '1', category: 'groente-fruit' },
      { name: 'Paprika', quantity: '1', category: 'groente-fruit' },
      { name: 'Feta', quantity: '150 g', category: 'zuivel' },
      { name: 'Olijven', quantity: '50 g', category: 'conserven-pasta' },
      { name: 'Uien', quantity: '0.5', category: 'groente-fruit' },
      { name: 'Olijfolie', quantity: '3 el', category: 'conserven-pasta' },
      { name: 'Oregano', quantity: '1 tl', category: 'overig' },
    ],
    steps: [
      'Snijd tomaten, komkommer en paprika in grote stukken.',
      'Snijd de rode ui in ringen.',
      'Verdeel feta en olijven erover.',
      'Besprenkel met olijfolie en oregano.',
    ],
    source: 'Grieks recept',
  },
  {
    id: 'r8',
    name: 'Nasi Goreng',
    description: 'Indonesische gebakken rijst met groenten en ei.',
    servings: 4,
    prepTime: 15,
    cookTime: 15,
    tags: ['aziatisch', 'indonesisch', 'snel'],
    ingredients: [
      { name: 'Rijst', quantity: '400 g', category: 'conserven-pasta' },
      { name: 'Kipfilet', quantity: '300 g', category: 'vlees-vis' },
      { name: 'Eieren', quantity: '4', category: 'zuivel' },
      { name: 'Prei', quantity: '1', category: 'groente-fruit' },
      { name: 'Wortels', quantity: '2', category: 'groente-fruit' },
      { name: 'Knoflook', quantity: '3 tenen', category: 'groente-fruit' },
      { name: 'Ketjap', quantity: '3 el', category: 'conserven-pasta' },
      { name: 'Sambal', quantity: '1 el', category: 'conserven-pasta' },
      { name: 'Zonnebloemolie', quantity: '2 el', category: 'conserven-pasta' },
      { name: 'Kroepoek', quantity: '1 zak', category: 'snacks' },
    ],
    steps: [
      'Kook de rijst en laat afkoelen.',
      'Snijd kip en groenten in kleine stukjes.',
      'Bak kip gaar in olie.',
      'Voeg groenten toe en roerbak.',
      'Voeg rijst, ketjap en sambal toe.',
      'Bak eieren apart als spiegelei.',
      'Serveer met kroepoek en gebakken ei.',
    ],
    source: 'Indonesisch recept',
  },
  {
    id: 'r9',
    name: 'Quiche Lorraine',
    description: 'Franse hartige taart met spek en kaas.',
    servings: 6,
    prepTime: 20,
    cookTime: 40,
    tags: ['frans', 'oven', 'klassiek'],
    ingredients: [
      { name: 'Bladerdeeg', quantity: '1 vel', category: 'diepvries' },
      { name: 'Bacon', quantity: '150 g', category: 'vlees-vis' },
      { name: 'Goudse kaas', quantity: '100 g', category: 'zuivel' },
      { name: 'Eieren', quantity: '3', category: 'zuivel' },
      { name: 'Kookroom', quantity: '200 ml', category: 'zuivel' },
      { name: 'Melk', quantity: '100 ml', category: 'zuivel' },
      { name: 'Peper', quantity: 'naar smaak', category: 'overig' },
      { name: 'Nootmuskaat', quantity: '1 snufje', category: 'overig' },
    ],
    steps: [
      'Verwarm de oven voor op 180°C.',
      'Bekleed een taartvorm met bladerdeeg.',
      'Bak de spekjes knapperig.',
      'Klop eieren, room, melk en kruiden.',
      'Verdeel spek en kaas over de bodem.',
      'Giet het eimengsel erover.',
      'Bak 35-40 minuten goudbruin.',
    ],
    source: 'Frans recept',
  },
  {
    id: 'r10',
    name: 'Burrito Bowl',
    description: 'Mexicaans geïnspireerde bowl met rijst, bonen en avocado.',
    servings: 2,
    prepTime: 15,
    cookTime: 20,
    tags: ['mexicaans', 'snel', 'gezond'],
    ingredients: [
      { name: 'Rijst', quantity: '200 g', category: 'conserven-pasta' },
      { name: 'Kidneybonen', quantity: '1 blik', category: 'conserven-pasta' },
      { name: 'Avocado', quantity: '1', category: 'groente-fruit' },
      { name: 'Tomaten', quantity: '2', category: 'groente-fruit' },
      { name: 'Mais blik', quantity: '1 blik', category: 'conserven-pasta' },
      { name: 'Sla', quantity: '100 g', category: 'groente-fruit' },
      { name: 'Crème fraîche', quantity: '100 g', category: 'zuivel' },
      { name: 'Limoenen', quantity: '1', category: 'groente-fruit' },
      { name: 'Komijn', quantity: '1 tl', category: 'overig' },
      { name: 'Paprikapoeder', quantity: '1 tl', category: 'overig' },
    ],
    steps: [
      'Kook de rijst gaar.',
      'Verwarm kidneybonen met komijn en paprika.',
      'Snijd avocado en tomaat.',
      'Verdeel rijst over kommen.',
      'Top met bonen, mais, avocado, tomaat en sla.',
      'Afmaken met crème fraîche en limoen.',
    ],
    source: 'Mexicaans recept',
  },
  {
    id: 'r11',
    name: 'Erwtensoep',
    description: 'Stevige Hollandse snert met rookworst.',
    servings: 6,
    prepTime: 15,
    cookTime: 120,
    tags: ['hollands', 'soep', 'winter', 'comfortfood'],
    ingredients: [
      { name: 'Spliterwten', quantity: '500 g', category: 'conserven-pasta' },
      { name: 'Rookworst', quantity: '1', category: 'vlees-vis' },
      { name: 'Prei', quantity: '2', category: 'groente-fruit' },
      { name: 'Selderij', quantity: '3 stengels', category: 'groente-fruit' },
      { name: 'Wortels', quantity: '3', category: 'groente-fruit' },
      { name: 'Aardappelen', quantity: '3', category: 'groente-fruit' },
      { name: 'Speklapjes', quantity: '200 g', category: 'vlees-vis' },
      { name: 'Roggebrood', quantity: '1 pakje', category: 'brood-bakkerij' },
    ],
    steps: [
      'Week de erwten een nacht.',
      'Kook speklapjes en erwten 1 uur.',
      'Voeg groenten toe en kook nog 1 uur.',
      'Verwarm rookworst in de soep.',
      'Serveer met roggebrood en mosterd.',
    ],
    source: 'Hollands recept',
  },
  {
    id: 'r12',
    name: 'Shakshuka',
    description: 'Eieren gepocheerd in pittige tomatensaus.',
    servings: 2,
    prepTime: 10,
    cookTime: 20,
    tags: ['vegetarisch', 'snel', 'ontbijt', 'midden-oosters'],
    ingredients: [
      { name: 'Eieren', quantity: '4', category: 'zuivel' },
      { name: 'Gepelde tomaten', quantity: '400 g', category: 'conserven-pasta' },
      { name: 'Paprika', quantity: '1', category: 'groente-fruit' },
      { name: 'Uien', quantity: '1', category: 'groente-fruit' },
      { name: 'Knoflook', quantity: '2 tenen', category: 'groente-fruit' },
      { name: 'Komijn', quantity: '1 tl', category: 'overig' },
      { name: 'Paprikapoeder', quantity: '1 tl', category: 'overig' },
      { name: 'Feta', quantity: '50 g', category: 'zuivel' },
      { name: 'Stokbrood', quantity: '1', category: 'brood-bakkerij' },
    ],
    steps: [
      'Fruit ui, paprika en knoflook.',
      'Voeg kruiden en tomaten toe, laat 10 min pruttelen.',
      'Maak kuiltjes en breek eieren erin.',
      'Deksel erop, 5-8 min pocheren.',
      'Verkruimel feta erover en serveer met brood.',
    ],
    source: 'Midden-Oosters recept',
  },
  {
    id: 'r13',
    name: 'Carbonara',
    description: 'Authentieke Italiaanse carbonara met ei en Pecorino.',
    servings: 4,
    prepTime: 10,
    cookTime: 15,
    tags: ['pasta', 'italiaans', 'snel', 'klassiek'],
    ingredients: [
      { name: 'Spaghetti', quantity: '400 g', category: 'conserven-pasta' },
      { name: 'Bacon', quantity: '200 g', category: 'vlees-vis' },
      { name: 'Eieren', quantity: '4', category: 'zuivel' },
      { name: 'Parmezaan', quantity: '80 g', category: 'zuivel' },
      { name: 'Peper', quantity: 'ruim', category: 'overig' },
    ],
    steps: [
      'Kook de spaghetti al dente.',
      'Bak de spekjes knapperig.',
      'Klop eieren met geraspte kaas en peper.',
      'Meng hete pasta met spek.',
      'Haal van het vuur en roer het eimengsel erdoor.',
    ],
    source: 'Italiaans recept',
  },
  {
    id: 'r14',
    name: 'Curry met Kikkererwten',
    description: 'Romige vegetarische curry met kikkererwten en spinazie.',
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    tags: ['vegetarisch', 'indiaas', 'gezond', 'curry'],
    ingredients: [
      { name: 'Kikkererwten', quantity: '2 blikken', category: 'conserven-pasta' },
      { name: 'Spinazie', quantity: '200 g', category: 'groente-fruit' },
      { name: 'Kokosmmelk blik', quantity: '400 ml', category: 'conserven-pasta' },
      { name: 'Uien', quantity: '1', category: 'groente-fruit' },
      { name: 'Knoflook', quantity: '3 tenen', category: 'groente-fruit' },
      { name: 'Gember', quantity: '2 cm', category: 'groente-fruit' },
      { name: 'Kerrie', quantity: '2 el', category: 'overig' },
      { name: 'Kurkuma', quantity: '1 tl', category: 'overig' },
      { name: 'Basmatirijst', quantity: '300 g', category: 'conserven-pasta' },
      { name: 'Naan brood', quantity: '4', category: 'brood-bakkerij' },
    ],
    steps: [
      'Fruit ui, knoflook en gember.',
      'Voeg kerrie en kurkuma toe.',
      'Voeg kokosmelk en kikkererwten toe.',
      'Laat 15 min sudderen.',
      'Roer spinazie erdoor.',
      'Serveer met rijst en naanbrood.',
    ],
    source: 'Indiaas recept',
  },
  {
    id: 'r15',
    name: 'Stamppot Boerenkool',
    description: 'Hollandse stamppot met boerenkool en rookworst.',
    servings: 4,
    prepTime: 15,
    cookTime: 30,
    tags: ['hollands', 'winter', 'comfortfood', 'stamppot'],
    ingredients: [
      { name: 'Aardappelen', quantity: '1 kg', category: 'groente-fruit' },
      { name: 'Boerenkool', quantity: '500 g', category: 'groente-fruit' },
      { name: 'Rookworst', quantity: '1', category: 'vlees-vis' },
      { name: 'Melk', quantity: '100 ml', category: 'zuivel' },
      { name: 'Boter', quantity: '30 g', category: 'zuivel' },
      { name: 'Mosterd', quantity: '2 el', category: 'conserven-pasta' },
    ],
    steps: [
      'Kook aardappelen gaar.',
      'Kook boerenkool kort mee.',
      'Stamp alles met melk en boter.',
      'Verwarm de rookworst.',
      'Serveer met mosterd en jus.',
    ],
    source: 'Hollands recept',
  },
  {
    id: 'r16',
    name: 'Fish & Chips',
    description: 'Knapperig gebakken vis met dikke friet.',
    servings: 2,
    prepTime: 15,
    cookTime: 25,
    tags: ['brits', 'vis', 'klassiek'],
    ingredients: [
      { name: 'Kabeljauw', quantity: '2 filets', category: 'vlees-vis' },
      { name: 'Bloem', quantity: '150 g', category: 'brood-bakkerij' },
      { name: 'Bier', quantity: '200 ml', category: 'dranken' },
      { name: 'Frites', quantity: '500 g', category: 'diepvries' },
      { name: 'Citroenen', quantity: '1', category: 'groente-fruit' },
      { name: 'Zout', quantity: 'naar smaak', category: 'overig' },
    ],
    steps: [
      'Maak beslag van bloem, bier en zout.',
      'Haal vis door het beslag.',
      'Frituur vis goudbruin.',
      'Bak frites knapperig.',
      'Serveer met citroen.',
    ],
    source: 'Brits recept',
  },
  {
    id: 'r17',
    name: 'Overnight Oats',
    description: 'Makkelijk ontbijt dat je de avond ervoor maakt.',
    servings: 1,
    prepTime: 5,
    cookTime: 0,
    tags: ['ontbijt', 'snel', 'gezond', 'vegetarisch'],
    ingredients: [
      { name: 'Havermout', quantity: '50 g', category: 'conserven-pasta' },
      { name: 'Yoghurt', quantity: '100 g', category: 'zuivel' },
      { name: 'Melk', quantity: '100 ml', category: 'zuivel' },
      { name: 'Honing', quantity: '1 el', category: 'conserven-pasta' },
      { name: 'Blauwe bessen', quantity: '50 g', category: 'groente-fruit' },
      { name: 'Bananen', quantity: '0.5', category: 'groente-fruit' },
    ],
    steps: [
      'Meng havermout, yoghurt, melk en honing.',
      'Zet afgedekt in de koelkast.',
      'Top de volgende ochtend met fruit.',
    ],
    source: 'Gezond recept',
  },
  {
    id: 'r18',
    name: 'Lasagne',
    description: 'Klassieke lasagne met lagen pasta, ragù en bechamelsaus.',
    servings: 6,
    prepTime: 30,
    cookTime: 45,
    tags: ['italiaans', 'oven', 'klassiek', 'comfortfood'],
    ingredients: [
      { name: 'Lasagne bladen', quantity: '250 g', category: 'conserven-pasta' },
      { name: 'Rundergehakt', quantity: '500 g', category: 'vlees-vis' },
      { name: 'Gepelde tomaten', quantity: '800 g', category: 'conserven-pasta' },
      { name: 'Uien', quantity: '2', category: 'groente-fruit' },
      { name: 'Knoflook', quantity: '3 tenen', category: 'groente-fruit' },
      { name: 'Wortels', quantity: '2', category: 'groente-fruit' },
      { name: 'Melk', quantity: '500 ml', category: 'zuivel' },
      { name: 'Boter', quantity: '40 g', category: 'zuivel' },
      { name: 'Bloem', quantity: '40 g', category: 'brood-bakkerij' },
      { name: 'Mozzarella', quantity: '200 g', category: 'zuivel' },
      { name: 'Parmezaan', quantity: '60 g', category: 'zuivel' },
    ],
    steps: [
      'Maak ragù: bak gehakt met ui, knoflook, wortel en tomaten.',
      'Maak bechamel: smelt boter, roer bloem erdoor, voeg melk toe.',
      'Laag in een ovenschaal: ragù, lasagne, bechamel. Herhaal.',
      'Top met mozzarella en Parmezaan.',
      'Bak 45 min op 180°C.',
    ],
    source: 'Italiaans recept',
  },
  {
    id: 'r19',
    name: 'Gazpacho',
    description: 'Verfrissende koude Spaanse tomatensoep.',
    servings: 4,
    prepTime: 15,
    cookTime: 0,
    tags: ['soep', 'vegetarisch', 'snel', 'spaans', 'zomer'],
    ingredients: [
      { name: 'Tomaten', quantity: '6', category: 'groente-fruit' },
      { name: 'Komkommer', quantity: '1', category: 'groente-fruit' },
      { name: 'Paprika', quantity: '1', category: 'groente-fruit' },
      { name: 'Knoflook', quantity: '1 teen', category: 'groente-fruit' },
      { name: 'Olijfolie', quantity: '3 el', category: 'conserven-pasta' },
      { name: 'Azijn', quantity: '2 el', category: 'conserven-pasta' },
      { name: 'Stokbrood', quantity: '1 stuk', category: 'brood-bakkerij' },
    ],
    steps: [
      'Snijd alle groenten grof.',
      'Blend alles glad met olijfolie en azijn.',
      'Breng op smaak met zout en peper.',
      'Koel minimaal 1 uur.',
      'Serveer met croutons.',
    ],
    source: 'Spaans recept',
  },
  {
    id: 'r20',
    name: 'Wraps met Kip en Guacamole',
    description: 'Gevulde wraps met gekruide kip en verse guacamole.',
    servings: 4,
    prepTime: 15,
    cookTime: 10,
    tags: ['mexicaans', 'snel', 'kindvriendelijk'],
    ingredients: [
      { name: 'Wraps', quantity: '4', category: 'brood-bakkerij' },
      { name: 'Kipfilet', quantity: '400 g', category: 'vlees-vis' },
      { name: 'Avocado', quantity: '2', category: 'groente-fruit' },
      { name: 'Tomaten', quantity: '2', category: 'groente-fruit' },
      { name: 'Sla', quantity: '100 g', category: 'groente-fruit' },
      { name: 'Limoenen', quantity: '1', category: 'groente-fruit' },
      { name: 'Crème fraîche', quantity: '100 g', category: 'zuivel' },
      { name: 'Komijn', quantity: '1 tl', category: 'overig' },
      { name: 'Paprikapoeder', quantity: '1 tl', category: 'overig' },
    ],
    steps: [
      'Kruid kip met komijn en paprika, bak gaar.',
      'Prak avocado met limoen en zout.',
      'Verwarm wraps.',
      'Vul met sla, kip, guacamole, tomaat en crème fraîche.',
      'Rol op en serveer.',
    ],
    source: 'Mexicaans recept',
  },
  {
    id: 'r21',
    name: 'Couscous met Geroosterde Groenten',
    description: 'Lichte couscous met geroosterde Mediterrane groenten.',
    servings: 4,
    prepTime: 15,
    cookTime: 30,
    tags: ['vegetarisch', 'gezond', 'mediterraans'],
    ingredients: [
      { name: 'Couscous', quantity: '300 g', category: 'conserven-pasta' },
      { name: 'Courgette', quantity: '2', category: 'groente-fruit' },
      { name: 'Paprika', quantity: '2', category: 'groente-fruit' },
      { name: 'Aubergine', quantity: '1', category: 'groente-fruit' },
      { name: 'Feta', quantity: '100 g', category: 'zuivel' },
      { name: 'Olijfolie', quantity: '3 el', category: 'conserven-pasta' },
      { name: 'Komijn', quantity: '1 tl', category: 'overig' },
      { name: 'Munt', quantity: '1 bosje', category: 'groente-fruit' },
    ],
    steps: [
      'Snijd groenten in grote stukken.',
      'Rooster 25 min op 200°C met olie en komijn.',
      'Bereid couscous met heet water.',
      'Meng alles en verkruimel feta erover.',
      'Garneer met verse munt.',
    ],
    source: 'Mediterraans recept',
  },
  {
    id: 'r22',
    name: 'Appeltaart',
    description: 'Klassieke Hollandse appeltaart met kaneel.',
    servings: 8,
    prepTime: 30,
    cookTime: 60,
    tags: ['hollands', 'bakken', 'dessert', 'klassiek'],
    ingredients: [
      { name: 'Appels', quantity: '6', category: 'groente-fruit' },
      { name: 'Bloem', quantity: '300 g', category: 'brood-bakkerij' },
      { name: 'Boter', quantity: '200 g', category: 'zuivel' },
      { name: 'Suiker', quantity: '150 g', category: 'overig' },
      { name: 'Eieren', quantity: '1', category: 'zuivel' },
      { name: 'Kaneel', quantity: '2 tl', category: 'overig' },
      { name: 'Rozijnen', quantity: '75 g', category: 'overig' },
      { name: 'Bakpoeder', quantity: '1 tl', category: 'overig' },
    ],
    steps: [
      'Maak deeg van bloem, boter, 100g suiker, ei en bakpoeder.',
      'Laat 30 min rusten in de koelkast.',
      'Schil en snijd appels, meng met kaneel, suiker en rozijnen.',
      'Bekleed een springvorm met 2/3 deeg.',
      'Vul met appelmengsel.',
      'Maak repen van de rest van het deeg voor het tralie.',
      'Bak 60 min op 170°C.',
    ],
    source: 'Hollands recept',
  },
  {
    id: 'r23',
    name: 'Ramen',
    description: 'Japanse noedelsoep met rijke bouillon en ei.',
    servings: 2,
    prepTime: 15,
    cookTime: 20,
    tags: ['aziatisch', 'japans', 'soep', 'comfortfood'],
    ingredients: [
      { name: 'Noodles', quantity: '200 g', category: 'conserven-pasta' },
      { name: 'Kippenbouillon', quantity: '800 ml', category: 'overig' },
      { name: 'Sojasaus', quantity: '3 el', category: 'conserven-pasta' },
      { name: 'Eieren', quantity: '2', category: 'zuivel' },
      { name: 'Kipfilet', quantity: '200 g', category: 'vlees-vis' },
      { name: 'Bosui', quantity: '3', category: 'groente-fruit' },
      { name: 'Champignons', quantity: '100 g', category: 'groente-fruit' },
      { name: 'Gember', quantity: '2 cm', category: 'groente-fruit' },
      { name: 'Knoflook', quantity: '2 tenen', category: 'groente-fruit' },
      { name: 'Spinazie', quantity: '50 g', category: 'groente-fruit' },
    ],
    steps: [
      'Kook eieren 6.5 min voor zacht gekookt.',
      'Verwarm bouillon met gember, knoflook en sojasaus.',
      'Kook noedels apart.',
      'Bak kip en champignons.',
      'Verdeel noedels over kommen, giet bouillon erover.',
      'Top met kip, ei, bosui en spinazie.',
    ],
    source: 'Japans recept',
  },
  {
    id: 'r24',
    name: 'Bananenbrood',
    description: 'Sappig bananenbrood, perfect om rijpe bananen te gebruiken.',
    servings: 8,
    prepTime: 10,
    cookTime: 55,
    tags: ['bakken', 'vegetarisch', 'ontbijt', 'dessert'],
    ingredients: [
      { name: 'Bananen', quantity: '3 rijpe', category: 'groente-fruit' },
      { name: 'Bloem', quantity: '200 g', category: 'brood-bakkerij' },
      { name: 'Suiker', quantity: '100 g', category: 'overig' },
      { name: 'Eieren', quantity: '2', category: 'zuivel' },
      { name: 'Boter', quantity: '80 g', category: 'zuivel' },
      { name: 'Bakpoeder', quantity: '1 tl', category: 'overig' },
      { name: 'Kaneel', quantity: '1 tl', category: 'overig' },
      { name: 'Walnoten', quantity: '50 g', category: 'snacks' },
    ],
    steps: [
      'Verwarm oven voor op 175°C.',
      'Prak bananen fijn.',
      'Meng gesmolten boter met suiker en eieren.',
      'Voeg bloem, bakpoeder en kaneel toe.',
      'Roer bananen en walnoten erdoor.',
      'Bak 50-55 min in een cakevorm.',
    ],
    source: 'Bakrecept',
  },
  {
    id: 'r25',
    name: 'Thai Groene Curry',
    description: 'Romige Thaise curry met groenten en kokosmelk.',
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    tags: ['aziatisch', 'thais', 'curry', 'snel'],
    ingredients: [
      { name: 'Kipfilet', quantity: '400 g', category: 'vlees-vis' },
      { name: 'Kokosmmelk blik', quantity: '400 ml', category: 'conserven-pasta' },
      { name: 'Broccoli', quantity: '200 g', category: 'groente-fruit' },
      { name: 'Paprika', quantity: '1', category: 'groente-fruit' },
      { name: 'Courgette', quantity: '1', category: 'groente-fruit' },
      { name: 'Sperziebonen', quantity: '100 g', category: 'groente-fruit' },
      { name: 'Basilicum', quantity: '1 bosje', category: 'groente-fruit' },
      { name: 'Jasminrijst', quantity: '300 g', category: 'conserven-pasta' },
      { name: 'Sojasaus', quantity: '1 el', category: 'conserven-pasta' },
      { name: 'Limoenen', quantity: '1', category: 'groente-fruit' },
    ],
    steps: [
      'Bak kip in stukjes.',
      'Voeg groene currypasta en kokosmelk toe.',
      'Voeg groenten toe.',
      'Laat 15 min sudderen.',
      'Serveer met jasminrijst en basilicum.',
    ],
    source: 'Thais recept',
  },
  {
    id: 'r26',
    name: 'Pulled Pork Sandwich',
    description: 'Langzaam gegaard varkensvlees op een broodje.',
    servings: 6,
    prepTime: 15,
    cookTime: 240,
    tags: ['amerikaans', 'bbq', 'comfortfood'],
    ingredients: [
      { name: 'Varkenshaas', quantity: '1 kg', category: 'vlees-vis' },
      { name: 'Bolletjes', quantity: '6', category: 'brood-bakkerij' },
      { name: 'Ketchup', quantity: '100 ml', category: 'conserven-pasta' },
      { name: 'Honing', quantity: '2 el', category: 'conserven-pasta' },
      { name: 'Mosterd', quantity: '2 el', category: 'conserven-pasta' },
      { name: 'Paprikapoeder', quantity: '2 tl', category: 'overig' },
      { name: 'Knoflookpoeder', quantity: '1 tl', category: 'overig' },
      { name: 'Sla', quantity: '100 g', category: 'groente-fruit' },
    ],
    steps: [
      'Wrijf het vlees in met kruiden.',
      'Braad aan en zet in de oven op 140°C.',
      'Laat 4 uur garen.',
      'Trek het vlees uit elkaar met twee vorken.',
      'Meng met BBQ saus (ketchup, honing, mosterd).',
      'Serveer op broodjes met sla.',
    ],
    source: 'Amerikaans recept',
  },
  {
    id: 'r27',
    name: 'Bruschetta',
    description: 'Geroosterd brood met tomaat, basilicum en knoflook.',
    servings: 4,
    prepTime: 10,
    cookTime: 5,
    tags: ['italiaans', 'snel', 'vegetarisch', 'snack'],
    ingredients: [
      { name: 'Ciabatta', quantity: '1', category: 'brood-bakkerij' },
      { name: 'Tomaten', quantity: '4', category: 'groente-fruit' },
      { name: 'Basilicum', quantity: '1 bosje', category: 'groente-fruit' },
      { name: 'Knoflook', quantity: '2 tenen', category: 'groente-fruit' },
      { name: 'Olijfolie', quantity: '3 el', category: 'conserven-pasta' },
      { name: 'Balsamico', quantity: '1 el', category: 'conserven-pasta' },
    ],
    steps: [
      'Snijd ciabatta in plakken, grill of rooster.',
      'Wrijf met knoflook.',
      'Snijd tomaten en meng met basilicum, olie en balsamico.',
      'Schep op het brood.',
    ],
    source: 'Italiaans recept',
  },
  {
    id: 'r28',
    name: 'Huisgemaakte Hamburgers',
    description: 'Sappige hamburgers met alles erop en eraan.',
    servings: 4,
    prepTime: 15,
    cookTime: 10,
    tags: ['amerikaans', 'bbq', 'kindvriendelijk'],
    ingredients: [
      { name: 'Rundergehakt', quantity: '500 g', category: 'vlees-vis' },
      { name: 'Bolletjes', quantity: '4 hamburger', category: 'brood-bakkerij' },
      { name: 'Sla', quantity: '4 bladeren', category: 'groente-fruit' },
      { name: 'Tomaten', quantity: '2', category: 'groente-fruit' },
      { name: 'Uien', quantity: '1', category: 'groente-fruit' },
      { name: 'Goudse kaas', quantity: '4 plakken', category: 'zuivel' },
      { name: 'Ketchup', quantity: 'naar smaak', category: 'conserven-pasta' },
      { name: 'Mayonaise', quantity: 'naar smaak', category: 'conserven-pasta' },
    ],
    steps: [
      'Meng gehakt met zout en peper, vorm 4 burgers.',
      'Gril of bak 4-5 min per kant.',
      'Leg kaas op de burgers, laat smelten.',
      'Rooster de broodjes.',
      'Beleg met sla, tomaat, ui en sauzen.',
    ],
    source: 'Klassiek recept',
  },
  {
    id: 'r29',
    name: 'Pompoensoep',
    description: 'Fluweelzachte soep van geroosterde pompoen.',
    servings: 4,
    prepTime: 15,
    cookTime: 40,
    tags: ['soep', 'vegetarisch', 'herfst', 'comfortfood'],
    ingredients: [
      { name: 'Pompoen', quantity: '1 kg', category: 'groente-fruit' },
      { name: 'Uien', quantity: '1', category: 'groente-fruit' },
      { name: 'Knoflook', quantity: '2 tenen', category: 'groente-fruit' },
      { name: 'Groentebouillon', quantity: '600 ml', category: 'overig' },
      { name: 'Kookroom', quantity: '100 ml', category: 'zuivel' },
      { name: 'Olijfolie', quantity: '2 el', category: 'conserven-pasta' },
      { name: 'Nootmuskaat', quantity: '1 snufje', category: 'overig' },
      { name: 'Stokbrood', quantity: '1', category: 'brood-bakkerij' },
    ],
    steps: [
      'Rooster pompoenblokjes 25 min op 200°C.',
      'Fruit ui en knoflook.',
      'Voeg pompoen en bouillon toe.',
      'Pureer glad en roer room erdoor.',
      'Breng op smaak met nootmuskaat.',
      'Serveer met knapperig brood.',
    ],
    source: 'Seizoensrecept',
  },
  {
    id: 'r30',
    name: 'Poke Bowl',
    description: 'Hawaiiaanse bowl met rijst, zalm en groenten.',
    servings: 2,
    prepTime: 20,
    cookTime: 15,
    tags: ['aziatisch', 'gezond', 'vis', 'snel'],
    ingredients: [
      { name: 'Zalmfilet', quantity: '250 g sashimi', category: 'vlees-vis' },
      { name: 'Rijst', quantity: '200 g', category: 'conserven-pasta' },
      { name: 'Avocado', quantity: '1', category: 'groente-fruit' },
      { name: 'Komkommer', quantity: '0.5', category: 'groente-fruit' },
      { name: 'Sojasaus', quantity: '3 el', category: 'conserven-pasta' },
      { name: 'Sesam', quantity: '1 el', category: 'overig' },
      { name: 'Bosui', quantity: '2', category: 'groente-fruit' },
      { name: 'Mango', quantity: '0.5', category: 'groente-fruit' },
    ],
    steps: [
      'Kook de rijst.',
      'Snijd zalm in blokjes, marineer in sojasaus.',
      'Snijd avocado, komkommer en mango.',
      'Verdeel rijst over kommen.',
      'Top met zalm, groenten en sesam.',
    ],
    source: 'Hawaiiaans recept',
  },
];

// Alle unieke tags met minimaal 2 recepten
export function getAllTags(): string[] {
  const tagCount = new Map<string, number>();
  RECIPES.forEach((r) => r.tags.forEach((t) => tagCount.set(t, (tagCount.get(t) || 0) + 1)));
  return Array.from(tagCount.entries())
    .filter(([, count]) => count >= 2)
    .sort((a, b) => b[1] - a[1])
    .map(([tag]) => tag);
}

export function getRecipeById(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}

export function scaleQuantity(qty: string, scale: number): string {
  const match = qty.match(/^([\d.,]+)\s*(.*)$/);
  if (!match) return qty;
  const num = parseFloat(match[1].replace(',', '.'));
  const unit = match[2];
  const scaled = num * scale;
  const formatted = scaled % 1 === 0 ? scaled.toString() : scaled.toFixed(1);
  return `${formatted} ${unit}`.trim();
}
